version: '3.9'

services:
  server:
    image: rezababapour/shell-runner:0.1.0
    container_name: runner
    hostname: runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker:/root/.docker
      - ./config.toml:/etc/gitlab-runner/config.toml
